;;;; scripts/build-page.lisp — wrap the artifact fragment into a standalone page.
;;;;
;;;; docs/concept.html is written as an *Artifact fragment*: it deliberately
;;;; has no doctype, no <html>, no <head> and no <body>, because the Artifact
;;;; host supplies that skeleton (and a small CSS reset) at publish time.
;;;;
;;;; A plain static web server supplies none of it.  Served raw, the fragment
;;;; puts the browser in quirks mode and has no viewport meta, so the layout
;;;; is subtly wrong on desktop and badly wrong on a phone.  This wraps it
;;;; into a standalone document for GitHub Pages — or any other static host —
;;;; hoisting <title> and <style> into the head where they belong.
;;;;
;;;; One source, two consumers: edit docs/concept.html, never docs/index.html.
;;;;
;;;; Run: make page

(defparameter *in*  #p"docs/concept.html")
(defparameter *out* #p"docs/index.html")

(defparameter *description*
  "Design concept for a 2D ant colony simulator on the SBCL/OpenGL stack, where every behaviour traces to a published mechanism.")

;;; The Artifact skeleton ships a minimal reset; a static host does not, so
;;; the equivalent is inlined here.  Keep it minimal — the page's own CSS is
;;; the design, this only replaces what the host would otherwise provide.
(defparameter *reset* "
    html { -webkit-text-size-adjust: 100%; }
    body { margin: 0; }
    *, *::before, *::after { box-sizing: border-box; }
    img, canvas { max-width: 100%; height: auto; }")

(defun slurp (path)
  (with-open-file (in path :external-format :utf-8)
    (let ((s (make-string (file-length in))))
      (subseq s 0 (read-sequence s in)))))

(defun cut (text open close)
  "Values: the first OPEN..CLOSE block's inner text, and TEXT without it.
Returns NIL and TEXT unchanged when the block is absent."
  (let* ((a (search open text))
         (b (and a (search close text :start2 a))))
    (if b
        (values (subseq text (+ a (length open)) b)
                (concatenate 'string
                             (subseq text 0 a)
                             (subseq text (+ b (length close)))))
        (values nil text))))

(defun main ()
  (unless (probe-file *in*)
    (format *error-output* "~&build-page: ~a not found~%" *in*)
    (sb-ext:quit :unix-status 1))
  (let ((text (slurp *in*))
        (title nil) (style nil))
    (multiple-value-setq (title text) (cut text "<title>" "</title>"))
    (multiple-value-setq (style text) (cut text "<style>" "</style>"))
    (unless (and title style)
      (format *error-output*
              "~&build-page: expected both <title> and <style> in ~a~%" *in*)
      (sb-ext:quit :unix-status 1))
    (with-open-file (out *out* :direction :output :external-format :utf-8
                               :if-exists :supersede :if-does-not-exist :create)
      (format out "<!doctype html>~%<html lang=\"en\">~%<head>~%")
      (format out "<meta charset=\"utf-8\">~%")
      (format out "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">~%")
      (format out "<meta name=\"description\" content=\"~a\">~%" *description*)
      (format out "<meta name=\"color-scheme\" content=\"light dark\">~%")
      (format out "<title>~a</title>~%" (string-trim '(#\Space #\Newline) title))
      (format out "<!-- Generated by scripts/build-page.lisp from docs/concept.html.~%~
                        Edit that file, then `make page`. -->~%")
      (format out "<style>~a~%~a</style>~%" *reset* style)
      (format out "</head>~%<body>~%")
      (write-string (string-left-trim '(#\Newline) text) out)
      (format out "~%</body>~%</html>~%"))
    (format t "~&build-page: ~a -> ~a~%" *in* *out*)))

(main)
